//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseTracker.View {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExpenseTrackerResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExpenseTrackerResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExpenseTracker.View.ExpenseTrackerResource", typeof(ExpenseTrackerResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Expense.
        /// </summary>
        internal static string AddExpense {
            get {
                return ResourceManager.GetString("AddExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Income.
        /// </summary>
        internal static string AddIncome {
            get {
                return ResourceManager.GetString("AddIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new Transaction.
        /// </summary>
        internal static string AddTransaction {
            get {
                return ResourceManager.GetString("AddTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [bold red]Exiting......[/].
        /// </summary>
        internal static string Exiting {
            get {
                return ResourceManager.GetString("Exiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [bold blue]Welcome To expense Tracker![/].
        /// </summary>
        internal static string ExpenseTracker {
            get {
                return ResourceManager.GetString("ExpenseTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the category of expense : .
        /// </summary>
        internal static string inputCategory {
            get {
                return ResourceManager.GetString("inputCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the date of Transaction ([bold white]DD/MM/YYYY[/] follow the exact format) : .
        /// </summary>
        internal static string inputDate {
            get {
                return ResourceManager.GetString("inputDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Amount Spent : .
        /// </summary>
        internal static string inputExpenseAmount {
            get {
                return ResourceManager.GetString("inputExpenseAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Amount earned : .
        /// </summary>
        internal static string inputIncomeAmount {
            get {
                return ResourceManager.GetString("inputIncomeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the source of income : .
        /// </summary>
        internal static string inputSource {
            get {
                return ResourceManager.GetString("inputSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [bold red]Invalid Input! please try again.[/].
        /// </summary>
        internal static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Main menu
        ///Select an option:.
        /// </summary>
        internal static string OptionSelection {
            get {
                return ResourceManager.GetString("OptionSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View transactions by date.
        /// </summary>
        internal static string transactionBydate {
            get {
                return ResourceManager.GetString("transactionBydate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Transaction.
        /// </summary>
        internal static string updateTransaction {
            get {
                return ResourceManager.GetString("updateTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Ledger.
        /// </summary>
        internal static string ViewAllTransaction {
            get {
                return ResourceManager.GetString("ViewAllTransaction", resourceCulture);
            }
        }
    }
}
