//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseTracker.View {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExpenseTrackerResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExpenseTrackerResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExpenseTracker.View.ExpenseTrackerResource", typeof(ExpenseTrackerResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [green]Expense Added[/].
        /// </summary>
        internal static string addedExpense {
            get {
                return ResourceManager.GetString("addedExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [green]Income Added[/].
        /// </summary>
        internal static string addedIncome {
            get {
                return ResourceManager.GetString("addedIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Expense.
        /// </summary>
        internal static string AddExpense {
            get {
                return ResourceManager.GetString("AddExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Income.
        /// </summary>
        internal static string AddIncome {
            get {
                return ResourceManager.GetString("AddIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the type of transaction.
        /// </summary>
        internal static string AddNewTransaction {
            get {
                return ResourceManager.GetString("AddNewTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new Transaction.
        /// </summary>
        internal static string AddTransaction {
            get {
                return ResourceManager.GetString("AddTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Transaction.
        /// </summary>
        internal static string DeleteTransaction {
            get {
                return ResourceManager.GetString("DeleteTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Transaction.
        /// </summary>
        internal static string EditTransaction {
            get {
                return ResourceManager.GetString("EditTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty record ! There are no transactions
        ///.
        /// </summary>
        internal static string empty {
            get {
                return ResourceManager.GetString("empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to exit ? (y or n) : .
        /// </summary>
        internal static string ExitConfirm {
            get {
                return ResourceManager.GetString("ExitConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [bold red]Exiting......[/]
        ///[bold]Press any key to exit[/].
        /// </summary>
        internal static string Exiting {
            get {
                return ResourceManager.GetString("Exiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense Amount.
        /// </summary>
        internal static string ExpenseAmountDiplay {
            get {
                return ResourceManager.GetString("ExpenseAmountDiplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense Records.
        /// </summary>
        internal static string ExpenseRecords {
            get {
                return ResourceManager.GetString("ExpenseRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [bold blue]Expense Tracker[/].
        /// </summary>
        internal static string ExpenseTracker {
            get {
                return ResourceManager.GetString("ExpenseTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income Amount.
        /// </summary>
        internal static string IncomeAmountDisplay {
            get {
                return ResourceManager.GetString("IncomeAmountDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income Records.
        /// </summary>
        internal static string IncomeRecords {
            get {
                return ResourceManager.GetString("IncomeRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Amount to update : .
        /// </summary>
        internal static string InputAmount {
            get {
                return ResourceManager.GetString("InputAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the category of expense : .
        /// </summary>
        internal static string inputCategory {
            get {
                return ResourceManager.GetString("inputCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the date of Transaction ([bold white]DD/MM/YYYY[/] follow the exact format) : .
        /// </summary>
        internal static string inputDate {
            get {
                return ResourceManager.GetString("inputDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Amount Spent : .
        /// </summary>
        internal static string inputExpenseAmount {
            get {
                return ResourceManager.GetString("inputExpenseAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Amount earned : .
        /// </summary>
        internal static string inputIncomeAmount {
            get {
                return ResourceManager.GetString("inputIncomeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the source of income : .
        /// </summary>
        internal static string inputSource {
            get {
                return ResourceManager.GetString("inputSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Transaction Id:.
        /// </summary>
        internal static string InputTransactionID {
            get {
                return ResourceManager.GetString("InputTransactionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [bold red]Invalid Input! please try again.[/]
        ///.
        /// </summary>
        internal static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Main menu
        ///Select an option:.
        /// </summary>
        internal static string OptionSelection {
            get {
                return ResourceManager.GetString("OptionSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [green]record deleted[/].
        /// </summary>
        internal static string RecordDeleted {
            get {
                return ResourceManager.GetString("RecordDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [bold]Total Amount[/].
        /// </summary>
        internal static string totalAmount {
            get {
                return ResourceManager.GetString("totalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View transactions by date.
        /// </summary>
        internal static string transactionBydate {
            get {
                return ResourceManager.GetString("transactionBydate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction ID.
        /// </summary>
        internal static string TransactionID {
            get {
                return ResourceManager.GetString("TransactionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Summary.
        /// </summary>
        internal static string TransactionSummary {
            get {
                return ResourceManager.GetString("TransactionSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remaining Tries :.
        /// </summary>
        internal static string tries {
            get {
                return ResourceManager.GetString("tries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [green]expense updated[/].
        /// </summary>
        internal static string UpdatedExpense {
            get {
                return ResourceManager.GetString("UpdatedExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [green]Income Updated[/].
        /// </summary>
        internal static string UpdatedIncome {
            get {
                return ResourceManager.GetString("UpdatedIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What change would you like to make?
        ///1. Date
        ///2. Amount
        ///3. Category
        ///.
        /// </summary>
        internal static string updateExpenseRecord {
            get {
                return ResourceManager.GetString("updateExpenseRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What change would you like to make?
        ///1. Date
        ///2. Amount
        ///3. Source
        ///.
        /// </summary>
        internal static string updateIncomeRecord {
            get {
                return ResourceManager.GetString("updateIncomeRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Transaction.
        /// </summary>
        internal static string updateTransaction {
            get {
                return ResourceManager.GetString("updateTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Ledger.
        /// </summary>
        internal static string ViewAllTransaction {
            get {
                return ResourceManager.GetString("ViewAllTransaction", resourceCulture);
            }
        }
    }
}
