//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManager.View {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InventoryManagerResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InventoryManagerResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InventoryManager.View.InventoryManagerResource", typeof(InventoryManagerResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application experienced an unexpected error and the application will be closed!
        ///The error message:.
        /// </summary>
        public static string ApplicationError {
            get {
                return ResourceManager.GetString("ApplicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |-----------Inventory Manager-----------|
        ///.
        /// </summary>
        public static string ConsoleName {
            get {
                return ResourceManager.GetString("ConsoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete by product ID.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [1/2/3/4] : .
        /// </summary>
        public static string Editchoices {
            get {
                return ResourceManager.GetString("Editchoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit by Product id.
        /// </summary>
        public static string editInput {
            get {
                return ResourceManager.GetString("editInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What change would you like to make?
        ///1. Product name
        ///2. Product Id
        ///3. Price of the product
        ///4. Quantity of the product
        ///.
        /// </summary>
        public static string EditOptions {
            get {
                return ResourceManager.GetString("EditOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no product in Inventory. 
        ///Empty inventory!.
        /// </summary>
        public static string EmptyInventory {
            get {
                return ResourceManager.GetString("EmptyInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string emptyline {
            get {
                return ResourceManager.GetString("emptyline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exiting application.
        /// </summary>
        public static string Exiting {
            get {
                return ResourceManager.GetString("Exiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [1/2/3/4/5/6] : .
        /// </summary>
        public static string InputChoices {
            get {
                return ResourceManager.GetString("InputChoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input. Please enter a correct value.
        /// </summary>
        public static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to          MENU
        ///1. Add new Product
        ///2. View all Products
        ///3. Search Product
        ///4. Delete Product
        ///5. Edit product
        ///6. Exit.
        /// </summary>
        public static string MenuDropDown {
            get {
                return ResourceManager.GetString("MenuDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to exit.
        /// </summary>
        public static string PressKey {
            get {
                return ResourceManager.GetString("PressKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Already exists. Enter a unique product Id or to edit product choose edit option..
        /// </summary>
        public static string ProductExists {
            get {
                return ResourceManager.GetString("ProductExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Unique Product ID : .
        /// </summary>
        public static string ProductID {
            get {
                return ResourceManager.GetString("ProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter product name : .
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product not found! Please try again with correct product details.
        /// </summary>
        public static string ProductNotFound {
            get {
                return ResourceManager.GetString("ProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the price of the product : .
        /// </summary>
        public static string ProductPrice {
            get {
                return ResourceManager.GetString("ProductPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Quantity of the product : .
        /// </summary>
        public static string ProductQuantity {
            get {
                return ResourceManager.GetString("ProductQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search product by ID.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your choice .
        /// </summary>
        public static string UserChoice {
            get {
                return ResourceManager.GetString("UserChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Successfully.
        /// </summary>
        public static string WrapperSuccess {
            get {
                return ResourceManager.GetString("WrapperSuccess", resourceCulture);
            }
        }
    }
}
